## Start up

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("dino_500.csv")
df

,occurrence_no,record_type,reid_no,flags,collection_no,accepted_name,accepted_attr,accepted_rank,accepted_no,early_interval,...,life_habit,vision,diet,reproduction,ontogeny,ecospace_comments,composition,architecture,thickness,reinforcement
0,139242,occ,24752.0,NaN,11890,Gorgosaurus libratus,NaN,species,53194,Late Campanian,...,"ground dwelling, solitary",NaN,carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN
1,139250,occ,23301.0,NaN,11893,Gorgosaurus libratus,NaN,species,53194,Late Campanian,...,"ground dwelling, solitary",NaN,carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN
2,139251,occ,NaN,NaN,11894,Centrosaurus apertus,NaN,species,63911,Late Campanian,...,ground dwelling,NaN,herbivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN
3,139252,occ,23302.0,NaN,11895,Gorgosaurus libratus,NaN,species,53194,Late Campanian,...,"ground dwelling, solitary",NaN,carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN
4,139253,occ,18699.0,NaN,11896,Gorgosaurus libratus,NaN,species,53194,Late Campanian,...,"ground dwelling, solitary",NaN,carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,480306,occ,34162.0,NaN,14453,Troodon formosus,NaN,species,54818,Middle Campanian,...,ground dwelling,NaN,"carnivore, omnivore",oviparous,"accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN
496,481732,occ,33075.0,NaN,48124,Mymoorapelta maysi,NaN,species,57683,Tithonian,...,"ground dwelling, gregarious",NaN,herbivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN
497,481742,occ,NaN,NaN,28366,Allosaurus fragilis,NaN,species,52962,Late Kimmeridgian,...,"ground dwelling, solitary",NaN,carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN
498,481755,occ,NaN,NaN,48127,Camarasaurus supremus,NaN,species,54168,Kimmeridgian,...,"ground dwelling, gregarious",NaN,herbivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,thick,NaN
499,481756,occ,NaN,NaN,48127,Allosaurus fragilis,NaN,species,52962,Kimmeridgian,...,"ground dwelling, solitary",NaN,carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",NaN,hydroxyapatite,compact or dense,NaN,NaN

## Investigate the dataframe

In [3]:
df.head()        # Preview first 5 rows
df.info()        # Column types + non-null counts
df.describe()    # Summary stats for numeric columns
df.shape         # (Rows, Columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Columns: 132 entries, occurrence_no to reinforcement
dtypes: float64(25), int64(5), object(102)
memory usage: 515.8+ KB

(500, 132)

In [4]:
df = df.dropna(axis=1, how='all')    # Drop fully empty columns
df.isna().all(axis=1).sum()          # Check for empty entries

np.int64(0)

## Maximize column display

In [5]:
pd.set_option('display.max_columns', None)
df

,occurrence_no,record_type,reid_no,flags,collection_no,accepted_name,accepted_rank,accepted_no,early_interval,late_interval,max_ma,min_ma,ref_author,ref_pubyr,reference_no,phylum,class,order,family,genus,abund_value,abund_unit,lng,lat,occurrence_comments,collection_name,collection_aka,cc,state,county,latlng_basis,latlng_precision,altitude_value,altitude_unit,geogscale,geogcomments,paleomodel,geoplate,paleoage,paleolng,paleolat,cc.1,protected,direct_ma_value,direct_ma_error,direct_ma_unit,direct_ma_method,max_ma_value,max_ma_error,max_ma_unit,max_ma_method,min_ma_value,min_ma_error,min_ma_unit,min_ma_method,formation,geological_group,member,stratscale,zone,zone_type,localsection,localbed,localbedunit,localorder,regionalsection,regionalbed,regionalbedunit,regionalorder,stratcomments,lithdescript,lithology1,lithadj1,lithification1,minor_lithology1,fossilsfrom1,lithology2,lithadj2,lithification2,minor_lithology2,fossilsfrom2,environment,tectonic_setting,geology_comments,size_classes,articulated_parts,associated_parts,common_body_parts,rare_body_parts,feed_pred_traces,component_comments,pres_mode,preservation_quality,spatial_resolution,temporal_resolution,lagerstatten,concentration,orientation,abund_in_sediment,sorting,fragmentation,bioerosion,encrustation,preservation_comments,collection_type,collection_methods,museum,collection_coverage,collection_size,rock_censused,collectors,collection_dates,collection_comments,taxonomy_comments,research_group,taxon_environment,motility,life_habit,diet,reproduction,ontogeny,composition,architecture,thickness
0,139242,occ,24752.0,NaN,11890,Gorgosaurus libratus,species,53194,Late Campanian,NaN,83.60,72.20,Matthew and Brown 1922,1922,13165,Chordata,Saurischia,NO_ORDER_SPECIFIED,Tyrannosauridae,Gorgosaurus,1.0,specimens,-111.528732,50.740726,NaN,"RTMP Quarry 6, Sand Creek [AMNH]",Sternberg Quarry 54,CA,Alberta,NaN,estimated from map,6,669.0,meters,local area,"near Steveville, Alberta (now Dinosaur Provinc...",gplates,101,mid,-65.72,60.93,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dinosaur Park,Belly River,NaN,bed,NaN,NaN,NaN,NaN,NaN,NaN,Dinosaur Park,4.135,m,bottom to top,originally assigned to the Oldman Fm.,NaN,sandstone,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,"""channel""",NaN,NaN,macrofossils,many,NaN,NaN,NaN,NaN,NaN,body,good,NaN,snapshot,NaN,dispersed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,taxonomic,"selective quarrying,mechanical,field collection",AMNH,NaN,NaN,NaN,C. H. Sternberg,1917,NaN,NaN,vertebrate,terrestrial,actively mobile,"ground dwelling, solitary",carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,NaN
1,139250,occ,23301.0,NaN,11893,Gorgosaurus libratus,species,53194,Late Campanian,NaN,83.60,72.20,Russell 1970,1970,4205,Chordata,Saurischia,NO_ORDER_SPECIFIED,Tyrannosauridae,Gorgosaurus,1.0,specimens,-111.549347,50.737015,NaN,"RTMP Quarry 48, Steveville (UA)","Sternberg Quarry 48, U.A.1",CA,Alberta,NaN,stated in text,6,662.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",gplates,101,mid,-65.75,60.93,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dinosaur Park,Belly River,NaN,bed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,originally assigned to the Oldman Fm.,NaN,sandstone,NaN,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,"""channel""",NaN,NaN,macrofossils,NaN,NaN,NaN,NaN,NaN,NaN,body,NaN,parautochthonous,snapshot,NaN,dispersed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,paleoecologic,"selective quarrying,mechanical,field collection",NaN,NaN,NaN,NaN,G. F. Sternberg,1921,NaN,NaN,vertebrate,terrestrial,actively mobile,"ground dwelling, solitary",carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,NaN
2,139251,occ,NaN,NaN,11894,Centrosaurus apertus,species,63911,Late Campanian,NaN,83.60,72.20,Currie 2005,2005,16964,Chordata,Ornithischia,NO_ORDER_SPECIFIED,Ceratopsidae,Centrosaurus,1.0,individuals,-111.528931,50.737297,RTMP 94.164.1,RTMP Quarry 217,NaN,CA,Alberta,NaN,stated in text,6,670.0,meters,small collection,NaN,gplates,101,mid,-65.72,60.93,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dinosaur Park,Belly River,NaN,bed,NaN,NaN,NaN,NaN,NaN,NaN,Dinosaur Park,4.030,m,NaN,NaN,NaN,not reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,terrestrial indet.,NaN,NaN,macrofossils,NaN,NaN,NaN,NaN,NaN,NaN,body,NaN,NaN,snapshot,NaN,dispersed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,general faunal/floral,"selective quarrying,mechanical,field collection",TMP,NaN,NaN,NaN,Routley,1994,NaN,NaN,vertebrate,terrestrial,actively mobile,ground dwelling,herbivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,NaN
3,139252,occ,23302.0,NaN,11895,Gorgosaurus libratus,species,53194,Late Campanian,NaN,83.60,72.20,Russell 1970,1970,4205,Chordata,Saurischia,NO_ORDER_SPECIFIED,Tyrannosauridae,Gorgosaurus,1.0,individuals,-111.564636,50.723866,NMC 11593,"RTMP Quarry 74, Steveville","NMC, Sternberg Quarry 50, G.S.C.24",CA,Alberta,NaN,stated in text,6,708.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",gplates,101,mid,-65.78,60.93,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dinosaur Park,Belly River,NaN,bed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,originally assigned to the Oldman Fm.,"""sandstone, plant matter""",sandstone,NaN,NaN,carbonaceous,Y,NaN,NaN,NaN,NaN,NaN,channel lag,NaN,"""channel base""",macrofossils,NaN,NaN,NaN,NaN,NaN,NaN,body,good,parautochthonous,snapshot,NaN,dispersed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,taxonomic,"selective quarrying,mechanical,field collection",GSC,NaN,NaN,NaN,C. M. Sternberg,1917,NaN,NaN,vertebrate,terrestrial,actively mobile,"ground dwelling, solitary",carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,NaN
4,139253,occ,18699.0,NaN,11896,Gorgosaurus libratus,species,53194,Late Campanian,NaN,83.60,72.20,Russell 1970,1970,4205,Chordata,Saurischia,NO_ORDER_SPECIFIED,Tyrannosauridae,Gorgosaurus,1.0,individuals,-111.525337,50.740471,NaN,"RTMP Quarry 106, Sand Creek (75 ft level) [AMNH]","Sternberg quarry 57, A.M.8",CA,Alberta,NaN,stated in text,6,666.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",gplates,101,mid,-65.71,60.93,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dinosaur Park,Belly River,NaN,bed,NaN,NaN,NaN,NaN,NaN,NaN,Dinosaur Park,0.755,m,bottom to top,originally assigned to Oldman Fm.,NaN,not reported,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,terrestrial indet.,NaN,NaN,macrofossils,NaN,NaN,NaN,NaN,NaN,NaN,body,good,NaN,snapshot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,taxonomic,"selective quarrying,mechanical,field collection",AMNH,NaN,NaN,NaN,B. Brown & P. Kaisen,1913,NaN,NaN,vertebrate,terrestrial,actively mobile,"ground dwelling, solitary",carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,480306,occ,34162.0,NaN,14453,Troodon formosus,species,54818,Middle Campanian,NaN,83.60,72.20,Montellano 1988,1988,2601,Chordata,Saurischia,NO_ORDER_SPECIFIED,Troodontidae,Troodon,5.0,individuals,-112.664299,47.821400,individuals and egg clutches,"Egg Mountain, MOR TM-006","Willow Creek Anticline, WCA",US,Montana,Teton,based on political unit,4,NaN,NaN,outcrop,found during blasting by Shell Oil Co. ca. 20 ...,gplates,127,mid,-71.37,58.79,US,NaN,NaN,NaN,NaN,NaN,77.9,NaN,Ma,U/Pb,76.3,NaN,Ma,U/Pb,Two Medicine,Montana,Flag Butte,group of beds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"""lacustrine interval"" of member",NaN,"""carbonate""",very fine,NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,terrestrial indet.,NaN,NaN,"macrofossils,mesofossils",NaN,NaN,NaN,NaN,NaN,NaN,body,NaN,autochthonous,NaN,NaN,concentrated,preferred,NaN,NaN,NaN,NaN,NaN,NaN,general faunal/floral,"selective quarrying,surface (in situ),mechanic...",NaN,NaN,NaN,NaN,"F. Tannenbaum, R. Makela, J. Horner",1978–,NaN,"within ""Lithofacies 4,"" dated at 76.7 Ma (appa...",vertebrate,terrestrial,actively mobile,ground dwelling,"carnivore, omnivore",oviparous,"accretion,modification of parts",hydroxyapatite,compact or dense,NaN
496,481732,occ,33075.0,NaN,48124,Mymoorapelta maysi,species,57683,Tithonian,NaN,149.20,143.10,Kirkland et al. 1998,1998,12888,Chordata,Ornithischia,NO_ORDER_SPECIFIED,Nodosauridae,Mymoorapelta,1.0,individuals,-108.476669,38.853611,MWC 2610,"Hups Quarry, MWC Loc. 197","Cactus Park, CO-57",US,Colorado,Mesa,based on nearby landmark,seconds,NaN,NaN,small collection,"Cactus Park, ca. 29 KM S of Grand Junction, Me...",gplates,101,mid,-43.85,26.94,US,FED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morrison,NaN,Brushy Basin,bed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,middle to upper part of member (orig. reported...,"""hard sandstone matrix""; ""fine-grained with ma...",sandstone,"fine,intraclastic",lithified,NaN,Y,NaN,NaN,NaN,NaN,NaN,"""channel""",NaN,NaN,macrofossils,NaN,NaN,NaN,NaN,NaN,NaN,"body,mold/impression",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,taxonomic,"selective quarrying,surface (float),surface (i...",NaN,NaN,NaN,NaN,K. Hups,NaN,NaN,NaN,vertebrate,terrestrial,actively mobile,"ground dwelling, gregarious",herbivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,NaN
497,481742,occ,NaN,NaN,28366,Allosaurus fragilis,species,52962,Late Kimmeridgian,Early Tithonian,152.21,145.06,Marsh 1884,1884,12248,Chordata,Saurischia,NO_ORDER_SPECIFIED,NO_FAMILY_SPECIFIED,Allosaurus,1.0,specimens,-105.224701,38.539501,NaN,"Felch Quarry 1, Garden Park","CO-3, Marsh-Felch Quarry, Marsh Quarry, Oil Creek",US,Colorado,Fremont,stated in text,4,1861.0,meters,small collection,"11 km N of Cañon City, Colorado. NE 1/4 of SE ...",gplates,101,mid,-41.31,25.16,US,FED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morrison,NaN,Brushy Basin,group of beds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Recent radiometric dates for several Garden Pa...,"""the bones are for the most part found in a ve...",sandstone,"lenticular,current ripples,coarse,very coarse,...",lithified,NaN,Y,claystone,planar lamination,NaN,NaN,Y,"""channel""",NaN,"""river, lake, or estuary origin rather than co...","macrofossils,mesofossils",NaN,NaN,NaN,NaN,NaN,NaN,body,good,parautochthonous,snapshot,NaN,-bonebed,NaN,abundant,NaN,occasional,NaN,NaN,some distortion of bones. Bones accumulated as...,general faunal/floral,"selective quarrying,surface (in situ),mechanic...","CM,UNSM,YPM",NaN,NaN,NaN,"S. & M. Felch, J. B. Hatcher, & Utterback",1877–1903,"discovered 1869 or 1870 by Sarah Felch, but no...",NaN,vertebrate,terrestrial,actively mobile,"ground dwelling, solitary",carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,NaN
498,481755,occ,NaN,NaN,48127,Camarasaurus supremus,species,54168,Kimmeridgian,Tithonian,154.80,143.10,Cope 1877,1877,7239,Chordata,Saurischia,NO_ORDER_SPECIFIED,Camarasauridae,Camarasaurus,1.0,individuals,-105.231598,38.547501,AMNH 5760,"Cope Quarry I, Cope's Nipple",Saurian Hill,US,Colorado,Fremont,estimated from map,4,NaN,NaN,small collection,"Garden Park, N of Cañon City, CO. N side of Sa...",gplates,101,mid,-40.92,25.20,US,FED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morrison,NaN,Brushy Basin,bed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mudstone,"brown,red",NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,dry floodplain,NaN,NaN,macrofossils,NaN,NaN,NaN,NaN,tooth marks,bite marks on AMNH 5760,body,good,NaN,NaN,NaN,dispersed,NaN,few,NaN,occasional,NaN,NaN,NaN,taxonomic,"selective quarrying,mechanical,field collection",AMNH,NaN,NaN,NaN,O. Lucas,Mar 1877,NaN,NaN,vertebrate,terrestrial,actively mobile,"ground dwelling, gregarious",herbivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,thick
499,481756,occ,NaN,NaN,48127,Allosaurus fragilis,species,52962,Kimmeridgian,Tithonian,154.80,143.10,Cope 1877,1877,15653,Chordata,Saurischia,NO_ORDER_SPECIFIED,NO_FAMILY_SPECIFIED,Allosaurus,1.0,specimens,-105.231598,38.547501,AMNH (lost),"Cope Quarry I, Cope's Nipple",Saurian Hill,US,Colorado,Fremont,estimated from map,4,NaN,NaN,small collection,"Garden Park, N of Cañon City, CO. N side of Sa...",gplates,101,mid,-40.92,25.20,US,FED,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Morrison,NaN,Brushy Basin,bed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mudstone,"brown,red",NaN,NaN,Y,NaN,NaN,NaN,NaN,NaN,dry floodplain,NaN,NaN,macrofossils,NaN,NaN,NaN,NaN,tooth marks,bite marks on AMNH 5760,body,good,NaN,NaN,NaN,dispersed,NaN,few,NaN,occasional,NaN,NaN,NaN,taxonomic,"selective quarrying,mechanical,field collection",AMNH,NaN,NaN,NaN,O. Lucas,Mar 1877,NaN,NaN,vertebrate,terrestrial,actively mobile,"ground dwelling, solitary",carnivore,"oviparous, dispersal=direct/internal,mobile","accretion,modification of parts",hydroxyapatite,compact or dense,NaN

## Drop unnecessary columns

In [6]:
columns = """occurrence_no record_type reid_no flags collection_no accepted_rank ref_author ref_pubyr reference_no order occurrence_comments collection_name collection_aka latlng_basis paleomodel geoplate  
paleolng paleolat cc.1	protected	direct_ma_value	direct_ma_error	direct_ma_unit	direct_ma_method	max_ma_value	max_ma_error	max_ma_unit	max_ma_method	min_ma_value	min_ma_error	min_ma_unit	min_ma_method	
formation	geological_group	member	stratscale	zone	zone_type	localsection	localbed	localbedunit	localorder	regionalsection	regionalbed	regionalbedunit	regionalorder	stratcomments	lithdescript	
lithology1	lithadj1	lithification1	minor_lithology1	fossilsfrom1	lithology2	lithadj2	lithification2	minor_lithology2	fossilsfrom2	environment	tectonic_setting	geology_comments	size_classes	
articulated_parts	associated_parts	common_body_parts	rare_body_parts	feed_pred_traces	component_comments	pres_mode	preservation_quality	spatial_resolution	temporal_resolution	lagerstatten	concentration	
orientation	abund_in_sediment	sorting	fragmentation	bioerosion	encrustation	preservation_comments	collection_type	collection_methods	museum	collection_coverage	collection_size	rock_censused	collectors
collection_comments	taxonomy_comments	research_group	taxon_environment	motility	life_habit 
reproduction	ontogeny	composition	architecture	thickness"""

drop_columns = [f"{w}" for w in columns.split()] # Splits the column names into individual strings
df_drop = df.drop(columns=drop_columns)          # Drop the collected columns

In [7]:
df_drop

,accepted_name,accepted_no,early_interval,late_interval,max_ma,min_ma,phylum,class,family,genus,abund_value,abund_unit,lng,lat,cc,state,county,latlng_precision,altitude_value,altitude_unit,geogscale,geogcomments,paleoage,collection_dates,diet
0,Gorgosaurus libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,specimens,-111.528732,50.740726,CA,Alberta,NaN,6,669.0,meters,local area,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1917,carnivore
1,Gorgosaurus libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,specimens,-111.549347,50.737015,CA,Alberta,NaN,6,662.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1921,carnivore
2,Centrosaurus apertus,63911,Late Campanian,NaN,83.60,72.20,Chordata,Ornithischia,Ceratopsidae,Centrosaurus,1.0,individuals,-111.528931,50.737297,CA,Alberta,NaN,6,670.0,meters,small collection,NaN,mid,1994,herbivore
3,Gorgosaurus libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,individuals,-111.564636,50.723866,CA,Alberta,NaN,6,708.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1917,carnivore
4,Gorgosaurus libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,individuals,-111.525337,50.740471,CA,Alberta,NaN,6,666.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1913,carnivore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Troodon formosus,54818,Middle Campanian,NaN,83.60,72.20,Chordata,Saurischia,Troodontidae,Troodon,5.0,individuals,-112.664299,47.821400,US,Montana,Teton,4,NaN,NaN,outcrop,found during blasting by Shell Oil Co. ca. 20 ...,mid,1978–,"carnivore, omnivore"
496,Mymoorapelta maysi,57683,Tithonian,NaN,149.20,143.10,Chordata,Ornithischia,Nodosauridae,Mymoorapelta,1.0,individuals,-108.476669,38.853611,US,Colorado,Mesa,seconds,NaN,NaN,small collection,"Cactus Park, ca. 29 KM S of Grand Junction, Me...",mid,NaN,herbivore
497,Allosaurus fragilis,52962,Late Kimmeridgian,Early Tithonian,152.21,145.06,Chordata,Saurischia,NO_FAMILY_SPECIFIED,Allosaurus,1.0,specimens,-105.224701,38.539501,US,Colorado,Fremont,4,1861.0,meters,small collection,"11 km N of Cañon City, Colorado. NE 1/4 of SE ...",mid,1877–1903,carnivore
498,Camarasaurus supremus,54168,Kimmeridgian,Tithonian,154.80,143.10,Chordata,Saurischia,Camarasauridae,Camarasaurus,1.0,individuals,-105.231598,38.547501,US,Colorado,Fremont,4,NaN,NaN,small collection,"Garden Park, N of Cañon City, CO. N side of Sa...",mid,Mar 1877,herbivore
499,Allosaurus fragilis,52962,Kimmeridgian,Tithonian,154.80,143.10,Chordata,Saurischia,NO_FAMILY_SPECIFIED,Allosaurus,1.0,specimens,-105.231598,38.547501,US,Colorado,Fremont,4,NaN,NaN,small collection,"Garden Park, N of Cañon City, CO. N side of Sa...",mid,Mar 1877,carnivore

## Confirm changes

In [8]:
df = df_drop

Rename columns into readable names

In [18]:
df_renamed = df.rename(columns={
    'accepted_name': 'Accepted Taxon Name', 'accepted_no': 'Accepted Taxon ID', 
    'early_interval': 'Early Interval', 'late_interval': 'Late Interva', 
    'max_ma': 'Maximum Age (Ma)', 'min_ma': 'Minimum Age (Ma)', 
    'phylum': 'Phylum', 'class': 'Class', 'family': 'Family', 
    'genus': 'Genus', 'abund_value': 'Abundance Value', 
    'abund_unit': 'Abundance Unit', 'lng': 'Longitude', 
    'lat': 'Latitude', 'cc': 'Country Code', 
    'state': 'State', 'county': 'County',
    'latlng_precision': 'Coordinate Precision',
    'altitude_value': 'Altitude',
    'altitude_unit': 'Altitude Unit',
    'geogscale': 'Geographic Scale',
    'geogcomments': 'Location Comments', 
    'paleoage': 'Geologic Interval',
    'collection_dates': 'Collection Year',
    'diet': 'Diet'})
df_renamed

,Accepted Taxon Name,Accepted Taxon ID,Early Interval,Late Interva,Maximum Age (Ma),Minimum Age (Ma),Phylum,Class,Family,Genus,Abundance Value,Abundance Unit,Longitude,Latitude,Country Code,State,County,Coordinate Precision,Altitude,Altitude Unit,Geographic Scale,Location Comments,Geologic Interval,Collection Year,Diet
0,Gorgosaurus libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,specimens,-111.528732,50.740726,CA,Alberta,NaN,6,669.0,meters,local area,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1917,carnivore
1,Gorgosaurus libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,specimens,-111.549347,50.737015,CA,Alberta,NaN,6,662.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1921,carnivore
2,Centrosaurus apertus,63911,Late Campanian,NaN,83.60,72.20,Chordata,Ornithischia,Ceratopsidae,Centrosaurus,1.0,individuals,-111.528931,50.737297,CA,Alberta,NaN,6,670.0,meters,small collection,NaN,mid,1994,herbivore
3,Gorgosaurus libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,individuals,-111.564636,50.723866,CA,Alberta,NaN,6,708.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1917,carnivore
4,Gorgosaurus libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,individuals,-111.525337,50.740471,CA,Alberta,NaN,6,666.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1913,carnivore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Troodon formosus,54818,Middle Campanian,NaN,83.60,72.20,Chordata,Saurischia,Troodontidae,Troodon,5.0,individuals,-112.664299,47.821400,US,Montana,Teton,4,NaN,NaN,outcrop,found during blasting by Shell Oil Co. ca. 20 ...,mid,1978–,"carnivore, omnivore"
496,Mymoorapelta maysi,57683,Tithonian,NaN,149.20,143.10,Chordata,Ornithischia,Nodosauridae,Mymoorapelta,1.0,individuals,-108.476669,38.853611,US,Colorado,Mesa,seconds,NaN,NaN,small collection,"Cactus Park, ca. 29 KM S of Grand Junction, Me...",mid,NaN,herbivore
497,Allosaurus fragilis,52962,Late Kimmeridgian,Early Tithonian,152.21,145.06,Chordata,Saurischia,NO_FAMILY_SPECIFIED,Allosaurus,1.0,specimens,-105.224701,38.539501,US,Colorado,Fremont,4,1861.0,meters,small collection,"11 km N of Cañon City, Colorado. NE 1/4 of SE ...",mid,1877–1903,carnivore
498,Camarasaurus supremus,54168,Kimmeridgian,Tithonian,154.80,143.10,Chordata,Saurischia,Camarasauridae,Camarasaurus,1.0,individuals,-105.231598,38.547501,US,Colorado,Fremont,4,NaN,NaN,small collection,"Garden Park, N of Cañon City, CO. N side of Sa...",mid,Mar 1877,herbivore
499,Allosaurus fragilis,52962,Kimmeridgian,Tithonian,154.80,143.10,Chordata,Saurischia,NO_FAMILY_SPECIFIED,Allosaurus,1.0,specimens,-105.231598,38.547501,US,Colorado,Fremont,4,NaN,NaN,small collection,"Garden Park, N of Cañon City, CO. N side of Sa...",mid,Mar 1877,carnivore

## Confirm Changes

In [19]:
df = df_renamed

## Transform taxon name and diet into title case

In [21]:
df["Accepted Taxon Name"] = df["Accepted Taxon Name"].str.strip().str.title()
df["Diet"] = df["Diet"].str.strip().str.title()

## Change "Nan" values to a more context-appropriate value

In [24]:
df['Genus'] = df['Genus'].fillna("Unknown")
df['Diet'] = df['Diet'].fillna("Unknown")
df['Collection Year'] = df['Collection Year'].fillna("No data")

## Write the transformed dinosaur data to CSV

In [25]:
df

,Accepted Taxon Name,Accepted Taxon ID,Early Interval,Late Interva,Maximum Age (Ma),Minimum Age (Ma),Phylum,Class,Family,Genus,Abundance Value,Abundance Unit,Longitude,Latitude,Country Code,State,County,Coordinate Precision,Altitude,Altitude Unit,Geographic Scale,Location Comments,Geologic Interval,Collection Year,Diet
0,Gorgosaurus Libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,specimens,-111.528732,50.740726,CA,Alberta,NaN,6,669.0,meters,local area,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1917,Carnivore
1,Gorgosaurus Libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,specimens,-111.549347,50.737015,CA,Alberta,NaN,6,662.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1921,Carnivore
2,Centrosaurus Apertus,63911,Late Campanian,NaN,83.60,72.20,Chordata,Ornithischia,Ceratopsidae,Centrosaurus,1.0,individuals,-111.528931,50.737297,CA,Alberta,NaN,6,670.0,meters,small collection,NaN,mid,1994,Herbivore
3,Gorgosaurus Libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,individuals,-111.564636,50.723866,CA,Alberta,NaN,6,708.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1917,Carnivore
4,Gorgosaurus Libratus,53194,Late Campanian,NaN,83.60,72.20,Chordata,Saurischia,Tyrannosauridae,Gorgosaurus,1.0,individuals,-111.525337,50.740471,CA,Alberta,NaN,6,666.0,meters,small collection,"near Steveville, Alberta (now Dinosaur Provinc...",mid,1913,Carnivore
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Troodon Formosus,54818,Middle Campanian,NaN,83.60,72.20,Chordata,Saurischia,Troodontidae,Troodon,5.0,individuals,-112.664299,47.821400,US,Montana,Teton,4,NaN,NaN,outcrop,found during blasting by Shell Oil Co. ca. 20 ...,mid,1978–,"Carnivore, Omnivore"
496,Mymoorapelta Maysi,57683,Tithonian,NaN,149.20,143.10,Chordata,Ornithischia,Nodosauridae,Mymoorapelta,1.0,individuals,-108.476669,38.853611,US,Colorado,Mesa,seconds,NaN,NaN,small collection,"Cactus Park, ca. 29 KM S of Grand Junction, Me...",mid,No data,Herbivore
497,Allosaurus Fragilis,52962,Late Kimmeridgian,Early Tithonian,152.21,145.06,Chordata,Saurischia,NO_FAMILY_SPECIFIED,Allosaurus,1.0,specimens,-105.224701,38.539501,US,Colorado,Fremont,4,1861.0,meters,small collection,"11 km N of Cañon City, Colorado. NE 1/4 of SE ...",mid,1877–1903,Carnivore
498,Camarasaurus Supremus,54168,Kimmeridgian,Tithonian,154.80,143.10,Chordata,Saurischia,Camarasauridae,Camarasaurus,1.0,individuals,-105.231598,38.547501,US,Colorado,Fremont,4,NaN,NaN,small collection,"Garden Park, N of Cañon City, CO. N side of Sa...",mid,Mar 1877,Herbivore
499,Allosaurus Fragilis,52962,Kimmeridgian,Tithonian,154.80,143.10,Chordata,Saurischia,NO_FAMILY_SPECIFIED,Allosaurus,1.0,specimens,-105.231598,38.547501,US,Colorado,Fremont,4,NaN,NaN,small collection,"Garden Park, N of Cañon City, CO. N side of Sa...",mid,Mar 1877,Carnivore

In [26]:
df.to_csv("dino_data_cleaned.csv", index=False)